# Generated by Django 6.0.2 on 2026-02-23 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_estoque_quantidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='descricao',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
