# Generated by Django 6.0.2 on 2026-02-23 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_venda_data_venda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendafiada',
            name='quitado',
        ),
        migrations.AddField(
            model_name='vendafiada',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('parcial', 'Parcial'), ('pago', 'Pago')], default='pendente', max_length=20),
        ),
    ]
