# Generated by Django 6.0.2 on 2026-02-23 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_vendafiada_quitado_vendafiada_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendafiada',
            old_name='valor_pago',
            new_name='total_pago',
        ),
        migrations.AddField(
            model_name='vendafiada',
            name='total_pendente',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
