# Generated by Django 6.0.2 on 2026-02-23 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rename_valor_pago_vendafiada_total_pago_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendafiada',
            name='total_pendente',
        ),
    ]
