# Generated by Django 6.0.2 on 2026-02-23 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_vendafiada_forma_pagamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendafiada',
            name='forma_pagamento',
            field=models.CharField(blank=True, choices=[('dinheiro', 'Dinheiro'), ('cartao', 'Cartão'), ('pix', 'Pix'), ('outro', 'Outro')], default='pix', max_length=100, null=True),
        ),
    ]
