# Generated by Django 6.0.2 on 2026-02-24 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_vendafiada_forma_pagamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendafiada',
            name='forma_pagamento',
        ),
        migrations.AddField(
            model_name='venda',
            name='forma_pagamento',
            field=models.CharField(blank=True, choices=[('dinheiro', 'Dinheiro'), ('pix', 'Pix'), ('dinheiro_pix', 'Dinheiro + Pix')], default='pix', max_length=100, null=True),
        ),
    ]
