# Generated by Django 6.0.2 on 2026-03-02 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_vendafiada_forma_pagamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='desconto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
