# Generated by Django 6.0.2 on 2026-06-06 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_venda_desconto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendafiada',
            name='venda',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fiadas', to='core.venda'),
        ),
    ]
