# Generated by Django 6.0.2 on 2026-06-07 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_produto_estoque_minimo'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='taxa',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
