# Generated by Django 6.0.2 on 2026-06-07 21:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_organizacao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizacao',
            name='membros',
            field=models.ManyToManyField(blank=True, null=True, related_name='organizacoes', to=settings.AUTH_USER_MODEL),
        ),
    ]
