# Generated by Django 6.0.2 on 2026-06-21 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_alter_itemcompra_produto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='estoque_minimo',
            field=models.PositiveIntegerField(blank=True, default=5, null=True),
        ),
    ]
