# Generated by Django 6.0.2 on 2026-06-21 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_alter_produto_estoque_minimo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcompra',
            name='quantidade',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
