# Generated by Django 6.0.2 on 2026-06-21 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_alter_itemcompra_quantidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemvenda',
            name='quantidade',
            field=models.IntegerField(default=0),
        ),
    ]
