# Generated by Django 6.0.2 on 2026-06-22 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_alter_produto_estoque_minimo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produto',
            options={'ordering': ['nome']},
        ),
    ]
