# Generated by Django 6.0.2 on 2026-06-22 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_alter_produto_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produto',
            options={},
        ),
    ]
